apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
patches:
  - path: patch.yaml
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: payment-service
    path: remove-payment-readiness.yaml
images:
  - name: chaos-api-gateway
    newName: 470725743213.dkr.ecr.us-east-1.amazonaws.com/chaos-api-gateway
    newTag: latest
  - name: chaos-order-service
    newName: 470725743213.dkr.ecr.us-east-1.amazonaws.com/chaos-order-service
    newTag: latest
  - name: chaos-inventory-service
    newName: 470725743213.dkr.ecr.us-east-1.amazonaws.com/chaos-inventory-service
    newTag: latest
  - name: chaos-payment-service
    newName: 470725743213.dkr.ecr.us-east-1.amazonaws.com/chaos-payment-service
    newTag: latest
  - name: chaos-frontend
    newName: 470725743213.dkr.ecr.us-east-1.amazonaws.com/chaos-frontend
    newTag: latest
