apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: chaos-tooling
  namespace: argocd
spec:
  project: ai-chaos-gameday
  source:
    # TODO: Replace with your Git repository URL after publishing this repo.
    repoURL: https://github.com/AllanSolorzano/AllanLearningGenAI
    targetRevision: HEAD
    path: k8s/chaos
  destination:
    server: https://kubernetes.default.svc
    namespace: chaos-system
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
